server:
  port: 8081
spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:h2:mem:customer-db
  h2:
    console:
      enabled: true



