server:
  port: 8083

spring:
  application:
    name: order-service

  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    ma.enset.orderservice.services.CustomerRestClientService: debug
    ma.enset.orderservice.services.InventoryRestClientService: debug

feign:
  client:
    config:
      default:
        loggerlevel : full


